name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D clippy::all
